import './PrivacyPolicy.css';
import { Link } from 'react-router-dom';
const PrivacyPolicy = (props) => {
    const currentUser = localStorage.getItem('toDoCurrentUser')
    return (<>
        {!currentUser &&
            <div className='privacyPolicyHeader'>
                <Link to='/login'><div className="privacyPolicy"><h4>DCR-A1AT-201: Conditional Follow-Up Portal</h4></div></Link>
            </div>
        }
        <div className="privacyPolicyConainer container mt-5 mb-5">
            <div className='textContainer row justify-content-center'>
                <div className="privacyPolicy">
                    <div className="privacyPolicyBackBtn">
                        <Link to="/login" className="back-button">
                            <div className='backBtnTerms'></div> Back
                        </Link>
                        <h2>Privacy Policy</h2>
                    </div>
                    <hr />
                </div>
                <div className="text">
                    <h4>General</h4>
                    <p>The present Privacy Policy constitutes an integral part of the Terms of Use – a legally binding agreement between you and PCT Lab Research (PCT) (hereafter interchangeably referred to as “PCT”, "Us", "We", or "Our"). Any capitalized terms and definitions not specifically defined herein shall have the meaning assigned to them in the Terms of Use.</p>
                    <p>This Privacy Policy (“Policy”) is aimed to inform Our users (“Users”, “Your” or “You”) of Our policies and procedures regarding the collection, use, transfer and disclosure of information We receive from Users and/or Users submit (input) into the System. </p>
                    <p>This Policy does not apply to: (1) websites, applications or services that display or link to different privacy policies or statements; (2) relations between the medical institutions, staff and/or doctors and respective patients undergoing clinical trials of medicines; (3) relations between Client and PCT. We are not responsible for the actions of the Client, medical institutions, staff and/or doctors, as well as of any third party people or companies, to whom You might provide any personally identifiable information within the scope of Your use of the System. </p>
                    <p>By accessing into or using the System You explicitly and irrevocably consent and agree to the collection, use and disclosure of information We receive from You in relation to the access into and use of the System and information You otherwise input into the System in accordance with this Privacy Policy.</p>
                    <p>Please read this Privacy Policy carefully. Please do not access or start using the System if You have not done so, or if You do not agree to this Privacy Policy.</p>
                    <h4>Updates and Modifications</h4>
                    <p>PCT reserves the right to update this Privacy Policy at any time, in its sole discretion, to enhance its better performance and by posting changes through the following link:
                        <a href="http://a1at-cfu.studymonitoring.net/login">http://a1at-cfu.studymonitoring.net/</a>. The PCT also reserves the right, upon request of the Client, to modify and/or change the System. PCT may also, but not necessarily, give You an additional notice thereof, via messaging within the System or otherwise. If You continue to use the System (irrespective of Us giving You an additional notice as mentioned above) following the posting of updates, changes or modifications, You thereby explicitly and irrevocably agree to and accept the updates, changes or modifications. Except as otherwise stated, all amended terms shall automatically be effective from the day they are initially posted</p>
                    <p>If You at any point do not agree to any portion of then-current Privacy Policy, Your license to use the System shall immediately terminate, and You must immediately stop using the System.</p>
                    <h4>Collection and Use of Information</h4>
                    <p>You cannot access the System without the login and password of the user account generated by Us and provided to the Client. The only information we gather during Your use of the System through the user account allocated to You by the Client is from standard server logs. These include Your IP (Internet Protocol) address, domain name, browser type, operating system, and information such as the web site that referred You to Us, and the dates/times of those visits.</p>
                    <p>However, during the use of System no personally indefinable information is requested by the PCT or elsewhere submitted into the System. </p>
                    <p>In order to access Your user account within the System You need to receive a specifically generated login and password from the Client. The number, as well as terms and condition of provision of user accounts to medical institutions, staff and/or doctors is determined by the Client, upon their sole discretion and do not constitute a subject matter of this Privacy Policy. </p>
                    <p>During Your use of the System, the following information can be or elsewhere will be inputted and/or registered into the System: (1) medical and/or health data, (2) data on disease and their treatment procedure, (3) information on vitals of patients, (4) information on complications, if any, (5) medical output, (6) medical treatment results, (7) types, names, effects, application and other consumption details of medicine undergoing trials, (8) steps and procedure of clinical trials and/or any other patient related information from various clinical trials of medicines, 9) other information relevant to clinical trials (hereinafter jointly referred to as “Medical Data”). </p>
                    <p>We use information, including without limitation Medical Data, that You input into the System or elsewhere submit to Us to enable the Client to use such data as described below. Furthermore, we may use information regarding Your use of the System, including Medical Data that You input into the System, to ensure Your compliance with the Terms of Use. </p>
                    <p>The Client may use the information that is inputted into the System to (a) analyze the medical outcome of use of medicines undergoing clinical trials; (b) track, analyze, study, survey and examine the medical and/or health conditions of patients undergoing clinical trials, results of such trials, vitals of patients, their health conditions prior and after the use of medicines undergoing clinical trials; (c) generate and download various reports on the outcome, consequences or current state of all or any medicines undergoing clinical trials; (d) download aggregated data on the types of diseases, treatment procedures and outcomes as a result of clinical trials of medicines. As agreed between Us and the Client we may use the information for the above-mentioned purposes as well. Furthermore, we may use the information to: (a) contact You about Your use of the System, such as for administrative purposes and for ensuring Your compliance with the Terms of Use, as well as for requesting feedback or evaluation in relation to Your use of the System; (b) notify You about important changes to Our policies or the System;  (c) request feedback regarding the System and to improve the System; (d) make sure that the login via Your account is genuine. </p>
                    <h4><i>Information Collected via Use of the System </i></h4>
                    <p><i>Via Service Features</i></p>
                    <p>We may collect Your information in connection with input features of the System, such as when You submit or elsewhere upload patient and/or medicine related information via the System.</p>
                    <p><i>Via Log files</i></p>
                    <p>When You access Our System, We may collect standard information about Your computer/device, such as Your IP address, browser type and operating system version. We use this information to help diagnose problems with Our server, to administer the System, and to improve its quality. The information gathered during general browsing of the System is used to analyze trends and usage of the System and to improve its usefulness.. </p>
                    <h4>Disclosure of Collected Information</h4>
                    <p><i>Disclosure of Medical Data </i></p>
                    <p>You understand, that all or part of the information collected via the System will be used only for medical, biological and other research purposes by the Client and/or medical institutions, staff and/or doctors who initially inputted such Medical Data into the System, as well as their supervisors. The Medical Data contained within the System will not be disclosed to any third party by Us. However, We do not guarantee or elsewhere re-ensure You that Client or medical institutions, staff and/or doctors will not disclose the Medical Data contained within the System as per procedures and in accordance with the conditions of separate agreements concluded between Yourself and such institution, or in any other manner whatsoever. </p>
                    <p><i>Third Party Service Providers</i></p>
                    <p>We may use third party companies to perform services related to the System.  These services include data storage, database management and hosting services.  They are obligated to use the information available on the System only to perform tasks on Our behalf. </p>
                    <p><i>Safety, Security and Compliance with Law</i></p>
                    <p>Your information and other information on the System may be accessed and monitored as necessary to provide access into or use of the System and may be disclosed: (i) when We have a good faith belief that We are required to disclose the information in response to a legal process (for example, a court order); (ii) to satisfy any applicable laws or regulations (iii) where We believe that the System is  being used in the commission of an illegal activity, including to report such activity or to exchange information with other parties for the purposes of fraud prevention and credit risk reduction; (iv) when We have a good faith belief that there is an emergency that poses a threat to the health and/or safety of You, another person or the public generally; and (v) in order to protect the rights or property of PCT, including to enforce Our Terms of Use.</p>
                    <p><i>Change of Ownership</i></p>
                    <p>In the event PCT undergoes a restructuring, liquidation or sale of all or a portion of its assets, We may transfer all or part of Your information and other information within the System, to the successor organization or person in such transition.</p>
                    <h4>Data security</h4>
                    <p>Any information provided to Us by Users of the System is held with the utmost care and security, and will not be used in ways other than as set forth in this Privacy Policy or in ways to which You have explicitly consented. We employ a range of techniques and security measures to protect the information maintained in the System from loss, misuse, unauthorized access or disclosure, alteration or destruction. </p>
                    <p>However, no website or Internet transmission is completely secure, and We cannot guarantee that unauthorized access, hacking, data loss, or other breaches will never occur. Also, We cannot guarantee the security of Your data while it is being transmitted into the System (including, without limitation, when transmission occurs via messaging), and any transmission is at Your own risk. We assume no responsibility for the security of information. </p>
                    <h4>Contact Information</h4>
                    <p>If You have any questions about this Policy, please feel free to contact Us online through the System or by e-mail at info@pctlabresearch.com </p>
                </div>
            </div>
        </div>
    </>)
}

export default PrivacyPolicy;