export const authActionsType = {
    SET_USER: "SET-USER",
    SET_LOADING: "SET-LOADING",
    SET_ERROR: "SET-ERROR",
    GET_IS_ADMIN: "GET-IS-ADMIN",
    GET_LOGGED_IN: "GET-LOGGED-IN",
}
export const changePassActionsType = {
    CHANGE_PASSWORD_OPEN: "CHANGE-PASS-OPEN",
    CHANGE_PASSWORD_CLOSE: "CHANGE-PASS-CLOSE"
}